### ISSUE TITLE
Publish survey kit

### ISSUE THREAD

**Issue by bingen** [aragon/aragen#22]
`deploy-beta` and `deploy-survey` should be updated to use last kits from DAO-kits after upgrade to aragonOS 4

**Comment by sohkai** [comment]
@izqui I think this is done now with #15?

**Comment by izqui** [comment]
Survey kit is still not being published.

**Comment by 0xGabi** [comment]
```sh
The survey app failed on travis with VotingPanel.js:3:15: Cannot resolve dependency 'BN.js'.
```

Will look into it and release survey with next minor version.

Note: I had no problem locally.
