### ISSUE TITLE
Discussion: Move aragen to aragonCLI monorepo

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragen#29]
Open discussion about pros and cons of migrating this repo as a new package in aragonCLI. If we decide to migrate, what are the best strategy to maintain releases automated.

Quote of @sohkai about this topic:
> aragen would make sense to include in the repo, however its problem is that it has a fairly involved installation phase as well an automated release strategy through merges to master.

**Comment by sohkai** [comment]
We could probably configure travis to only release aragen on specific branch or commit names 🤷‍♂️. I do like moving this into aragon-cli, since it's mostly meant to be used there.

Alternatively this is always manually releasable, but is just a bit of a pain to wait for everything to build.

**Comment by 0xGabi** [comment]
No relevant anymore
