### ISSUE TITLE
Rename snapshot path from ~/.aragon/ganache-db-{version} to ~/.aragon/aragen-db-{version}

### ISSUE THREAD

**Issue by sohkai** [aragon/aragen#39]
Makes it a bit more clear where this snapshot is coming from, and the version associated to it (since it used to be the CLI's version, but is now aragen's version).

---
This issue is funded with **45 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).

**Funded**: [Mainnet Tx](https://etherscan.io/tx/0xc22f61e3fe92400033177e299cf65cce00905994655811367568a888765c3ce6)

**Comment by 0xGabi** [comment]
@fabriziovigevani can you provide me with a mainnet address.
