### ISSUE TITLE
Update ganache-vars mnemonic to use the same as @aragon/os/truffle-config

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragen#53]
As discussed in a recent conversation with @gh1dra: 
> Standarize across all apps, it just seemed annoying to always have to change the env variables when using the dao kit deployments

**Comment by sohkai** [comment]
We should do this in aragonOS, especially once moving its truffle config out to its own separate module: https://github.com/aragon/aragonOS/issues/538.
