### ISSUE TITLE
Configure initial account balances

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragen#74]
We are trying to use the ganache-core option `default_balance_ether` that is not working as expected.

Related issue: https://github.com/trufflesuite/ganache-core/issues/468

**Comment by sohkai** [comment]
@0xGabi I think we can close this now; there's probably no way for us to modify the starting eth when we're working off of a snapshot.

**Comment by 0xGabi** [comment]
Yes, you are right, I decided to use 10,000 ETH as start value cause I received feedback that it was needed for some use cases.
