### ISSUE TITLE
Ganache issue with transaction pathing

### ISSUE THREAD

**Issue by osarrouy** [aragon/aragen#75]
Hey !

There is an issue with the latest version of `@aragon/cli` because of `@aragon/aragen`. The way ganache informs the Aragon Client about the gas cost of failing transactions is weird so the client believes that anyone is always allowed to initiate a transaction and does not trigger transaction forwarding ... [making the transaction fail in the end].

Maybe it would be worth reverting to an old version of ganache ...

**Comment by 0xGabi** [comment]
My bad, I were not able to release yet. I will rollback `ganache-cli` that seems to be the source of the problem and publish a new version of aragen as a patch and next week will look in more detail if we can use a newer version than `6.2.5`
